name: Latest blog post workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 * * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   env:
     SSL_CERT_DIR: /etc/ssl/certs
     NODE_TLS_REJECT_UNAUTHORIZED: 0
   steps:
     - uses: actions/checkout@v2
     - uses: treideme/blog-post-workflow@master
       with:
         feed_list: "https://www.reidemeister.com/?feed=rss2"
         max_post_count: 25
